# Generated by Django 2.2.2 on 2021-06-17 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210614_0010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='structure',
            options={'verbose_name': 'organization', 'verbose_name_plural': 'organization'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['id'], 'verbose_name': 'usr info', 'verbose_name_plural': 'usr info'},
        ),
        migrations.AlterField(
            model_name='structure',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Structure', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='title',
            field=models.CharField(max_length=60, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='type',
            field=models.CharField(choices=[('firm', 'firm'), ('department', 'department')], default='department', max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Structure', verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('famale', 'famale')], default='male', max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='joined_date',
            field=models.DateField(blank=True, null=True, verbose_name='joined date'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='post',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, to='rbac.Role', verbose_name='roles'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='superior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='superior'),
        ),
    ]
