# Generated by Django 2.2.2 on 2021-06-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_structure_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='address',
            field=models.CharField(max_length=60, verbose_name='address'),
        ),
    ]
