# Generated by Django 2.2.2 on 2021-06-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210618_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='abn',
            field=models.CharField(max_length=60, verbose_name='abn'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='telephone',
            field=models.CharField(max_length=60, verbose_name='telephone'),
        ),
    ]
