# Generated by Django 2.2.2 on 2021-06-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210618_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='type',
            field=models.CharField(choices=[('firm', 'Extra-NLC'), ('department', 'Intra-NLC')], default='department', max_length=20, verbose_name='type'),
        ),
    ]
