# Generated by Django 2.2.2 on 2021-06-19 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_auto_20210617_1658'),
        ('personal', '0002_auto_20180607_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='explorationapplication',
            name='land',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='adm.Equipment', verbose_name='land'),
        ),
    ]
