# Generated by Django 2.2.2 on 2021-06-19 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_explorationapplication_land'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explorationapplication',
            name='land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.Equipment', verbose_name='land'),
        ),
    ]
