# Generated by Django 2.2.2 on 2021-06-19 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20210619_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explorationapplication',
            name='land',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='adm.Equipment', verbose_name='land'),
        ),
    ]
