# Generated by Django 2.2.2 on 2021-06-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_auto_20210619_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='explorationapplicationrecord',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='file/%Y/%m', verbose_name='实施文档'),
        ),
    ]
