# Generated by Django 2.2.2 on 2021-06-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0010_auto_20210622_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explorationapplication',
            name='type',
            field=models.CharField(choices=[('0', '初次安装'), ('1', '售后现场'), ('2', '远程支持'), ('3', '售前支持')], default='0', max_length=10, verbose_name='工单类型'),
        ),
    ]
