# Generated by Django 2.2.2 on 2021-06-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0011_auto_20210623_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explorationapplication',
            name='type',
            field=models.CharField(choices=[('0', 'Agent'), ('1', 'Applicant')], default='0', max_length=10, verbose_name='工单类型'),
        ),
    ]
