# Generated by Django 2.2.2 on 2021-06-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0012_auto_20210623_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explorationapplication',
            name='status',
            field=models.CharField(choices=[('0', 'Application returned'), ('1', 'Create-save'), ('2', 'Submitted-waiting for assess'), ('3', 'Assessed-waiting for receipt'), ('4', 'Receipted-waiting for comfirm'), ('5', 'Application finished')], default='0', max_length=10, verbose_name='工单状态'),
        ),
    ]
